name: Symfony CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: make ci-install

    - name: Run database migrations
      run: make migrate

    - name: Run code quality checks
      run: make check

    - name: Run tests
      run: make test

    - name: Show logs if failed
      if: failure()
      run: make logs
